
[workspace.package]
version = "0.0.5"
edition = "2021"
authors = ["Aldo Cortesi <aldo@corte.si>"]
description = "An interface to the Anthropic API"
license = "MIT"
repository = "https://github.com/cortesi/misanthropy"

[workspace]
resolver = "2"
members = ["crates/*"]
